### ISSUE TITLE
ltr/rtl or English/Arabic problems

### ISSUE THREAD

**Issue by MhdSyrwan** [wikitechie/elgg-facebook_theme#1]
we have some problems in displaying English/Arabic texts

**Comment by MhdSyrwan** [comment]
solved all texts that depend on output/text or output/longtext
still some problems , working on them ...

**Comment by isstaif** [comment]
I think it would be enough to change the direction property (i.e. dir=rtl), and to leave the alignment to the default value. It is confusing to read text from right to left and left to right in the same time. It is only important for the flow of the dual-lang text to be right.

**Comment by MhdSyrwan** [comment]
that won't solve the problem
i think this is the best existing solution
reopen if there is any more problems ?
