### ISSUE TITLE
Urgent Ajaxifying!

### ISSUE THREAD

**Issue by isstaif** [wikitechie/elgg-facebook_theme#2]
*Comment posting
*Likes

**Comment by MhdSyrwan** [comment]
will make an ajaxifying system that depends on elgg views and actions
so we type something like :

``` html
<a href='#like' data-guid='12' data-destContainer='#likeBox' >I like this </a>
```

to make a link to like the object with "guid=12"  automatically without any more code

Or we can make it more general , like this :

``` html
<a href='#action' data-guid='12' data-destContainer='#likeBox' data-action='wikiactivity/like' /> I like this </a>
```

and this will automatically linked with action actions/wikiactivity/like

and we can make a lot of these methods
