### ISSUE TITLE
Wiki Every Where

### ISSUE THREAD

**Issue by TamerShlash** [wikitechie/elgg-facebook_theme#21]
If we just add the wiki plugin as any other one, people might just use this social network as any other network and not give any attention to socialwiki, and thus the network might fail.

Wiki should be every where and should have a high priority so it becomes the general character of the network despite it's social nature, for example wiki edits should have higher priority in the wire and so on, also wiki options and buttons should be visible every where, tempting, and attractive, and make people really like and participate in wikis!

**Comment by MhdSyrwan** [comment]
it seems nice for this project ,but we should ask our selves : will users like it this way ?

**Comment by TamerShlash** [comment]
I think if you give users something nice, users will like it whatever it is!

Also they know that this is a wiki-oriented social network, so what do they expect? We are not Making them use wiki, because they are supposed to be using it already, we are only giving them all motivation they need.
